# CloudBroadcast.srv - Send data to cloud/other sites

# Request
string site_id
uint8 sync_type               # SYNC_* from CloudSync.msg
string payload_json
string[] destination_sites    # Empty = broadcast all
uint8 bandwidth_priority
bool require_acknowledgement
float32 timeout

---

# Response
bool success
string message
string sync_id
string[] acknowledged_sites
string[] failed_sites
float32 transmission_time     # seconds
