# GetFleetStatus.srv - Get status of all machines in the fleet
# Returns aggregated status, OEE, and queue information

# Request
string[] machine_filter           # Empty = all machines
bool include_oee                  # Include OEE metrics
bool include_queue                # Include job queue info
---
# Response
MachineStatus[] machines
OeeMetrics[] oee_data            # If include_oee=true
uint32 total_machines
uint32 machines_running
uint32 machines_idle
uint32 machines_alarm
uint32 machines_offline
float32 fleet_oee                # Average OEE across fleet
uint32 total_jobs_queued
