# ScheduleJobs.srv - Schedule or reschedule jobs

# Request
cnc_interfaces/ScheduleJob[] jobs_to_schedule
bool reschedule_all           # Reoptimize entire schedule
string optimization_goal      # "minimize_makespan", "minimize_lateness", "balance_load"

# Constraints
builtin_interfaces/Time schedule_horizon_start
builtin_interfaces/Time schedule_horizon_end
string[] available_machines
uint32 max_queue_per_machine

---

# Response
bool success
string message
cnc_interfaces/ScheduleJob[] scheduled_jobs
float32 schedule_efficiency   # 0.0-1.0
float32 estimated_makespan    # Total time to complete all jobs
uint32 jobs_scheduled
uint32 jobs_failed
string[] scheduling_warnings
