; LEGO Brick 2x4 - Sample Milling G-code
; Generated by LegoMCP Fusion 360 CAM
; Machine: GRBL
; Material: ABS Plastic
; 
; TOOLS USED:
;   T2 - 3mm Flat Endmill (Roughing)
;   T4 - 1mm Flat Endmill (Finishing)
;
; ESTIMATED TIME: 8.5 minutes
;

; === SETUP ===
G21 ; Metric units (mm)
G90 ; Absolute positioning
G94 ; Feed per minute mode

; === OPERATION 1: Adaptive Roughing ===
; Tool: T2 - 3mm Flat Endmill
; Stock to leave: 0.2mm

T2 M6 ; Tool change
S18000 M3 ; Spindle on, 18000 RPM
G4 P2 ; Dwell for spindle

; Rapid to start position
G0 X0 Y0 Z10

; Begin roughing passes
; ... (actual toolpath data would be here)

G0 Z10 ; Retract

; === OPERATION 2: Contour Finishing ===
; Tool: T4 - 1mm Flat Endmill

T4 M6 ; Tool change
S24000 M3 ; Spindle on, 24000 RPM
G4 P2

; ... (finishing passes)

; === END ===
G0 Z25 ; Safe retract
M5 ; Spindle off
G0 X0 Y0 ; Return to origin
M30 ; Program end
